apiVersion: v1
kind: Pod
metadata:
  name: graphql
spec:
  containers:
  - name: graphql
    image: hasura/graphql-engine:v2.3.1.cli-migrations-v3
    ports:
    - containerPort: 8080
    resources:
      limits:
        memory: "1Gi"
        cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: graphql
spec:
  selector:
    app: graphql
  ports:
  - protocol: TCP
    port: 8080