apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
  - name: postgres
    image: postgres:13
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_PASSWORD
      value: postgrespassword
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
