apiVersion: v1
kind: Pod
metadata:
  name: nextjs
spec:
  containers:
  - name: nextjs
    image: hasura-ecommerce-nextjs:latest
    ports:
    - containerPort: 3000
    volumeMounts:
    - name: app-volume
      mountPath: /usr/src/app-volume
    env:
    - name: DATABASE_HOST
      value: "DATABASE_HOST"
    - name: DATABASE_PORT
      value: "5432"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: app-volume
    emptyDir: {}