apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
spec:
  containers:
  - name: worker-pod
    image: vendure-docker-compose-worker:latest
    volumeMounts:
    - name: app-volume
      mountPath: /usr/src/app-volume
    env:
    - name: DATABASE_HOST
      value: "DATABASE_HOST"
    - name: DATABASE_PORT
      value: "5432"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: app-volume
    emptyDir: {}